### ISSUE TITLE
Not entirely OPEN-SOURCE !?

### ISSUE THREAD

**Issue by ahke-sied** [mnismt/CompressedCrack#2]
What the **UnRAR.exe** do there? It seem like not to be 100% open source ... Right?

**Comment by PeterMX** [comment]
It's the toot to check if the generated password is OK, it doesn't works in Linux you have to replace with "/usr/bin/unrar"

**Comment by mnismt** [comment]
This project is now licensed under the [MIT License](https://github.com/mnismt/CompressedCrack?tab=MIT-1-ov-file)!
