### ISSUE TITLE
Attribute time.clock() is not working...

### ISSUE THREAD

**Issue by Hardly-Human** [mnismt/CompressedCrack#6]
AttributeError: module 'time' has no attribute 'clock' 

solution: The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() to have well-defined behavior.

**Comment by fdciabdul** [comment]
Using python2 is working well

**Comment by Teraskull** [comment]
> AttributeError: module 'time' has no attribute 'clock'
> 
> solution: The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() to have well-defined behavior.

On Python versions >3.3, time.clock() is deprecated. Change "time.clock()" to "time.process_time()".

I will create a pull request.
