### ISSUE TITLE
sooo slow bro

### ISSUE THREAD

**Issue by eawlot3000** [mnismt/CompressedCrack#8]
so slow

**Comment by Korozin** [comment]
What did you expect? lmao. It's a bruteforce method which is trying every possible combination from the set of characters it's given and the legnth. Just for context only using charcters from `aA - zZ` with a password that's 6 characters long would already be a couple _billion_ combinations.

**Comment by mnismt** [comment]
> What did you expect? lmao. It's a bruteforce method which is trying every possible combination from the set of characters it's given and the legnth. Just for context only using charcters from `aA - zZ` with a password that's 6 characters long would already be a couple _billion_ combinations.
> 
> If you want to speed it up then I'd suggest trying to whittle down the amount of possibilities. Do you know if the password is all lowercase?, all uppercase?, does it have special characters? If you're able to determine that you can cut the character list in the file in order to speed up the process by only using relevant characters.

Thank you for providing a good explanation!
